name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Add package dependencies
        working-directory: src
        run: |
          mkdir package
          pip install -r requirements.txt --target .
          zip -r lambda.zip .

      - name: Update Lambda code
        working-directory: src
        run: |
          aws lambda update-function-code --function-name gpt --zip-file fileb://lambda.zip --region us-west-2
